name: mobile_kokosan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider_android: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  google_fonts: ^6.1.0 # Use a version where the conflict is resolved
  http: ^1.1.2
  provider: ^5.0.0
  url_launcher: ^6.0.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  sqflite: ^2.3.0
  path: ^1.8.3
  # google_maps_flutter: ^2.5.2
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  # qris: ^0.7.1
  # permission_handler: ^11.1.0
  qr_flutter: ^4.0.0
  upi_payment_qrcode_generator: ^1.4.0
  image_picker: ^0.8.3+2
  firebase_storage: ^11.6.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.0

  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/eye.png
    - assets/eye-off.png
    - assets/splash_image.png
    - assets/login.png
    - assets/btn_back.png
    - assets/btn_map.png
    - assets/btn_wishlist.png
    - assets/city1.png
    - assets/city2.png
    - assets/city3.png
    - assets/city4.png
    - assets/city5.png
    - assets/city6.png
    - assets/error.png
    - assets/home.png
    - assets/icon_bedroom.png
    - assets/icon_card.png
    - assets/icon_cupboard.png
    - assets/icon_email.png
    - assets/icon_home.png
    - assets/icon_kitchen.png
    - assets/icon_love.png
    - assets/icon_star_grey.png
    - assets/icon_star.png
    - assets/logo1.png
    - assets/logo2.png
    - assets/thumbnail.png
    - assets/tips1.png
    - assets/tips2.png
    - assets/qris.png