// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGY7_XdIQCE9IAjDB0Fd3aoc9UV0TFdY',
    appId: '1:628222595362:web:7f68c75475fd350d1e557b',
    messagingSenderId: '628222595362',
    projectId: 'kokosan-uasmobile',
    authDomain: 'kokosan-uasmobile.firebaseapp.com',
    storageBucket: 'kokosan-uasmobile.appspot.com',
    measurementId: 'G-M6D9PPJPWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPQhpCeTyjrdHmUYm227Vmp5_tavkRyk',
    appId: '1:628222595362:android:1d95391e8bf079771e557b',
    messagingSenderId: '628222595362',
    projectId: 'kokosan-uasmobile',
    storageBucket: 'kokosan-uasmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-3h84S2vTinxMmXfdeUd7Cd9djloYWg',
    appId: '1:628222595362:ios:44e1c1635b9481d11e557b',
    messagingSenderId: '628222595362',
    projectId: 'kokosan-uasmobile',
    storageBucket: 'kokosan-uasmobile.appspot.com',
    iosBundleId: 'com.example.mobileKokosan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-3h84S2vTinxMmXfdeUd7Cd9djloYWg',
    appId: '1:628222595362:ios:b452fdea992f89ad1e557b',
    messagingSenderId: '628222595362',
    projectId: 'kokosan-uasmobile',
    storageBucket: 'kokosan-uasmobile.appspot.com',
    iosBundleId: 'com.example.mobileKokosan.RunnerTests',
  );
}
